name = "PolyLog"
uuid = "85e3b03c-9856-11eb-0374-4dc1f8670e7f"
authors = ["Alexander Voigt <ahgvoigt@gmail.com>"]
version = "2.5.1"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[extensions]
PolyLogChainRulesExt = "ChainRulesCore"
PolyLogForwardDiffExt = "ForwardDiff"

[compat]
ChainRulesCore = "1"
ChainRulesTestUtils = "1"
ForwardDiff = "0.10,0.11,1"
julia = "1.0"

[extras]
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles", "ForwardDiff", "ChainRulesTestUtils"]
