name = "PolyLog"
uuid = "85e3b03c-9856-11eb-0374-4dc1f8670e7f"
authors = ["Alexander Voigt <ahgvoigt@gmail.com>"]
version = "1.3.0"

[compat]
julia = "1.0"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["Test", "DelimitedFiles"]
