name = "PolyLog"
uuid = "85e3b03c-9856-11eb-0374-4dc1f8670e7f"
authors = ["Alexander Voigt <ahgvoigt@gmail.com>"]
version = "2.4.2"

[compat]
julia = "1.0"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[weakdeps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"

[extensions]
PolyLogForwardDiffExt = "ForwardDiff"
PolyLogChainRulesExt = "ChainRulesCore"

[targets]
test = ["Test", "DelimitedFiles", "ForwardDiff"]
