name = "PolyLog"
uuid = "85e3b03c-9856-11eb-0374-4dc1f8670e7f"
authors = ["Alexander Voigt <alexander.voigt@hs-flensburg.de>"]
version = "2.0.0"

[compat]
julia = "1.0"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles"]
